ema_alpha:
  type: uniform
  default: 0.8001082519967331
  range: [0.7, 0.95]

max_cos_dist:
  type: uniform
  default: 0.34611618209067696
  range: [0.1, 0.4]

max_iou_dist:
  type: uniform
  default: 0.9263865388293092
  range: [0.5, 0.95]

max_age:
  type: randint
  default: 13
  range: [10, 151]

n_init:
  type: randint
  default: 3
  range: [1, 4]

mc_lambda:
  type: uniform
  default: 0.9734407921970812
  range: [0.9, 0.999]

nn_budget:
  type: choice
  default: 100
  options: [100]
